set(_CATKIN_CURRENT_PACKAGE "chefbot_bringup")
set(chefbot_bringup_VERSION "0.0.0")
set(chefbot_bringup_MAINTAINER "lentin <lentin@todo.todo>")
set(chefbot_bringup_PACKAGE_FORMAT "1")
set(chefbot_bringup_BUILD_DEPENDS "actionlib" "depthimage_to_laserscan" "geometry_msgs" "move_base_msgs" "nav_msgs" "openni_launch" "robot_pose_ekf" "robot_state_publisher" "roscpp" "rospy" "std_msgs" "tf")
set(chefbot_bringup_BUILD_EXPORT_DEPENDS "actionlib" "depthimage_to_laserscan" "geometry_msgs" "move_base_msgs" "nav_msgs" "openni_launch" "robot_pose_ekf" "robot_state_publisher" "roscpp" "rospy" "std_msgs" "tf")
set(chefbot_bringup_BUILDTOOL_DEPENDS "catkin")
set(chefbot_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(chefbot_bringup_EXEC_DEPENDS "actionlib" "depthimage_to_laserscan" "geometry_msgs" "move_base_msgs" "nav_msgs" "openni_launch" "robot_pose_ekf" "robot_state_publisher" "roscpp" "rospy" "std_msgs" "tf")
set(chefbot_bringup_RUN_DEPENDS "actionlib" "depthimage_to_laserscan" "geometry_msgs" "move_base_msgs" "nav_msgs" "openni_launch" "robot_pose_ekf" "robot_state_publisher" "roscpp" "rospy" "std_msgs" "tf")
set(chefbot_bringup_TEST_DEPENDS )
set(chefbot_bringup_DOC_DEPENDS )
set(chefbot_bringup_URL_WEBSITE "")
set(chefbot_bringup_URL_BUGTRACKER "")
set(chefbot_bringup_URL_REPOSITORY "")
set(chefbot_bringup_DEPRECATED "")